{% set name = "gw-sklearn-xarray" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mmann1123/sklearn-xarray/archive/refs/tags/v{{ version }}.tar.gz  
  sha256: 00c01f769d3bb4c74e90da9c5edd2fcf7c3f0c6d0ecbccc73b293231760fa5e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools

  run:
    - python >=3.8
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - xarray


test:
  imports:
    - sklearn_xarray

about:
  home: https://github.com/mmann1123/sklearn-xarray
  summary: 'a fork of sklearn-xarray for use in geowombat machine learning'
  description: |
    a fork of sklearn-xarray for use in geowombat machine learning
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/mmann1123/sklearn-xarray

extra:
  recipe-maintainers:
    - mmann1123
    - jgrss

